version: "3.7"

networks:
  clean-network:
  
services:
  blogapp-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M"
        ACCEPT_EULA: "Y"
    networks:
      - clean-network

  blogapp-mongodb:
    image: mongo
    restart: always
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - clean-network